// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./src/components/AppProvider/index.vue')['default']
    DialogContent: typeof import('./src/components/AppProvider/DialogContent.vue')['default']
    FetchList: typeof import('./src/components/index/FetchList.vue')['default']
    Header: typeof import('./src/components/common/header/index.vue')['default']
    LoadingBar: typeof import('./src/components/AppProvider/LoadingBar.vue')['default']
    MessageContent: typeof import('./src/components/AppProvider/MessageContent.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
  }
}

export { }
